@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json


# GET http://{{host}}/api/v1/task HTTP/1.1

//post user

# POST /users
POST http://{{host}}/api/v1/task HTTP/1.1
Content-Type: {{contentType}}
{
"name": "Shaheb Ali",
"isCompleted": true

}
